"""Update User Product Table

Revision ID: 49c43250b90d
Revises: 019d37efb4f2
Create Date: 2020-07-11 13:56:10.352093

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '49c43250b90d'
down_revision = '019d37efb4f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('user_id', sa.BigInteger(), nullable=True))
    op.drop_constraint('product_ibfk_1', 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'user', ['user_id'], ['uid'])
    op.drop_column('product', 'uid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('uid', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key('product_ibfk_1', 'product', 'user', ['uid'], ['uid'])
    op.drop_column('product', 'user_id')
    # ### end Alembic commands ###
